apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
  labels:
    app: mongo-express

spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      name: mongo-express-pod
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_USERNAME
              valueFrom:
                  secretKeyRef:
                    name: mongo-secrets
                    key: mongo-root-username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                  secretKeyRef:
                    name: mongo-secrets
                    key: mongo-root-password
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                  configMapKeyRef:
                    name: mongo-express-configmap
                    key: databaseURL